name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  tests-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
      - name: Install dependencies
        run: npm ci
      - name: run tests
        run: npm run cy_run